services:
  db:
    image: postgres:17
    container_name: postgres-db-jpa
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    networks:
      - backend
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
    container_name: java-jpa-app
    depends_on:
      - db
    networks:
      - backend
    ports:
      - "8080:8080"  # <-- ¡AÑADE ESTA LÍNEA!

  # --- INICIO DE LO NUEVO ---
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-jpa
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@proyecto.com"  # Email para iniciar sesión
      PGADMIN_DEFAULT_PASSWORD: "adminpass"      # CAMBIA ESTA CONTRASEÑA
    ports:
      - "5050:80"  # Accede en: http://localhost:5050
    networks:
      - backend    # Clave: se conecta a la misma red que la BD
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - db         # Se asegura de iniciarse después de la BD
  # --- FIN DE LO NUEVO ---

networks:
  backend:

volumes:
  pgdata:
  pgadmin-data: